/**
 * ประวัติและรายละเอียดบริษัท AIA — เนื้อหา HTML (ไม่ใส่ใน locale JSON)
 */
export const aiaCompanyHistoryAsiaBodies: Record<
  'th' | 'en' | 'lo',
  Record<number, string>
> = {
  th: {
    1: "<p>ในโลกของการวางแผนการเงินและ<b>การประกันชีวิต</b> ชื่อของ <b><u>AIA</u></b> ถือเป็นหนึ่งในบริษัทที่มีความน่าเชื่อถือและมีประสบการณ์ยาวนานที่สุดในเอเชีย โดยเฉพาะในประเทศไทยที่ AIA ได้รับความไว้วางใจจากลูกค้าหลายล้านราย</p><p>บทความนี้จะพาคุณไปรู้จักกับ<b>ประวัติความเป็นมา</b> และรายละเอียดของ AIA เพื่อช่วยให้คุณมั่นใจมากขึ้นก่อนตัดสินใจเลือกแผน เช่น <a href='/articles/aia-health-good-2026'><b>ประกันสุขภาพ AIA</b></a> หรือ <a href='/services'><b>ประกันชีวิต</b></a> ที่เหมาะกับตัวเอง</p>",
    2: "<p>บริษัท <b>AIA</b> หรือ <b>American International Assurance</b> ก่อตั้งขึ้นในปี ค.ศ. <b><u>1919</u></b> โดย Cornelius Vander Starr นักธุรกิจชาวอเมริกัน ที่เริ่มต้นธุรกิจประกันในภูมิภาคเอเชีย</p><p>สำนักงานใหญ่แห่งแรกตั้งอยู่ที่ <u>Shanghai</u> ก่อนที่บริษัทจะขยายธุรกิจไปยังหลายประเทศในเอเชีย และเติบโตอย่างต่อเนื่องจนกลายเป็นหนึ่งในบริษัทประกันชีวิตชั้นนำของโลก</p>",
    3: "<p>AIA ได้ขยายธุรกิจครอบคลุมหลายประเทศในภูมิภาคเอเชีย-แปซิฟิก ไม่ว่าจะเป็น:</p><ul><li>Thailand</li><li>Hong Kong</li><li>Singapore</li><li>China</li></ul><p>ปัจจุบัน AIA เป็นบริษัทที่มีลูกค้าหลายสิบล้านราย และมีตัวแทนประกันจำนวนมากในภูมิภาคเอเชีย หากคุณอยู่ในไทยและมองหาผู้เชี่ยวชาญในพื้นที่ แนะนำ <a href='/articles/agent-udon-free-consult'>ตัวแทน AIA อุดรธานีและภาคอีสาน</a></p>",
    4: "<p><b>AIA</b> เข้ามาดำเนินธุรกิจในประเทศไทยมานานกว่า <b><u>80 ปี</u></b> และถือเป็นหนึ่งในบริษัทประกันชีวิตที่มีฐานลูกค้าใหญ่ที่สุดในประเทศ</p><p>ด้วยความมั่นคงทางการเงิน และการพัฒนาผลิตภัณฑ์อย่างต่อเนื่อง ทำให้ AIA ได้รับความไว้วางใจจากคนไทยจำนวนมาก โดยเฉพาะในด้าน <a href='/services'><b>ประกันชีวิต</b></a> <a href='/articles/aia-health-good-2026'><b>ประกันสุขภาพ</b></a> และการวางแผนการเงินระยะยาว</p>",
    5: "<p><strong>1. ความมั่นคงและประสบการณ์ยาวนาน</strong><br/>ด้วยประสบการณ์มากกว่า <b>100 ปี</b> ทำให้ AIA มีความแข็งแกร่งทั้งด้านการบริหารและการเงิน</p><p><strong>2. ผลิตภัณฑ์หลากหลาย</strong><br/>AIA มีแผนประกันให้เลือกหลากหลาย เช่น <a href='/services'>ประกันชีวิต</a> <a href='/articles/health-coverage-what'>ประกันสุขภาพ</a> <a href='/articles/cancer-treatment-cost-thailand'>การคุ้มครองโรคร้ายแรง</a> — ตอบโจทย์ทั้งบุคคลทั่วไปและครอบครัว</p>",
    6: "<p><strong>3. บริการและตัวแทนมืออาชีพ</strong><br/>AIA มีตัวแทนที่ผ่านการอบรมและมีประสบการณ์ ช่วยให้ลูกค้าได้รับคำแนะนำที่เหมาะสม — อ่านเพิ่ม <a href='/articles/buy-through-agent-or-self'>ซื้อประกันกับตัวแทนหรือซื้อเอง</a></p><p><strong>4. การพัฒนาอย่างต่อเนื่อง</strong><br/>AIA ปรับตัวตามเทคโนโลยีและความต้องการของลูกค้า เช่น แอปพลิเคชันและบริการดิจิทัล</p><p><b>AIA</b> กับแนวคิด <b><u>“Health & Wellness”</u></b> — ไม่ได้เน้นแค่การขายประกัน แต่ยังส่งเสริมสุขภาพของลูกค้าในระยะยาว รวมถึงโปรแกรมอย่าง <a href='/articles/aia-vitality'><b>AIA Vitality</b></a></p>",
    7: "<p><strong>ทำไมควรเลือก AIA ผ่าน UDONAIA.COM</strong><br/>หากคุณกำลังมองหาข้อมูลหรือที่ปรึกษาด้านประกัน การเลือกช่องทางที่น่าเชื่อถือเป็นสิ่งสำคัญ เว็บไซต์ช่วยเรื่อง <a href='/articles/aia-health-good-2026'>ประกันสุขภาพ AIA</a> <a href='/services'>ประกันชีวิต</a> และการวางแผนการเงิน พร้อมคำปรึกษาจากทีมที่เข้าใจลูกค้าในพื้นที่ เช่น <a href='/articles/agent-udon-free-consult'>AIA อุดรธานี</a></p><p><strong>สรุป</strong><br/>AIA เป็นบริษัทประกันชีวิตที่มีประวัติยาวนาน และได้รับความไว้วางใจจากลูกค้าทั่วเอเชีย ด้วยความมั่นคง ผลิตภัณฑ์ที่หลากหลาย และการพัฒนาอย่างต่อเนื่อง</p><p><b><u>สนใจวางแผนชีวิตและสุขภาพ</u></b> <a href='/contact'><b>ติดต่อปรึกษาฟรีที่ udonaia.com</b></a></p>",
  },
  en: {
    1: "<p>In financial planning and <b>life insurance</b>, <b><u>AIA</u></b> is one of the most trusted names with a long track record in Asia — including Thailand, where millions of customers rely on AIA.</p><p>This article covers <b>AIA’s history and profile</b> so you can feel more confident before choosing a plan, such as <a href='/articles/aia-health-good-2026'><b>AIA health insurance</b></a> or <a href='/services'><b>life insurance</b></a> that fits you.</p>",
    2: "<p><b>AIA</b> (<b>American International Assurance</b>) was founded in <b><u>1919</u></b> by American entrepreneur Cornelius Vander Starr, starting the insurance business in Asia.</p><p>The first head office was in <u>Shanghai</u>, before expanding across Asia and growing into a leading global life insurer.</p>",
    3: "<p>AIA operates across Asia-Pacific, including:</p><ul><li>Thailand</li><li>Hong Kong</li><li>Singapore</li><li>China</li></ul><p>Today AIA serves tens of millions of customers with a large advisor force in Asia. In Thailand, see also <a href='/articles/agent-udon-free-consult'>AIA advisors in Udon Thani and the Northeast</a>.</p>",
    4: "<p><b>AIA</b> has done business in Thailand for more than <b><u>80 years</u></b> and is among the life insurers with one of the largest customer bases in the country.</p><p>Financial strength and continuous product development earn trust in <a href='/services'><b>life insurance</b></a>, <a href='/articles/aia-health-good-2026'><b>health insurance</b></a>, and long-term financial planning.</p>",
    5: "<p><strong>1. Stability and long experience</strong><br/>With more than <b>100 years</b> of history, AIA is strong in management and finance.</p><p><strong>2. Broad product range</strong><br/>Plans include <a href='/services'>life insurance</a>, <a href='/articles/health-coverage-what'>health insurance</a>, and <a href='/articles/cancer-treatment-cost-thailand'>serious illness protection</a> — for individuals and families.</p>",
    6: "<p><strong>3. Professional service and advisors</strong><br/>Trained advisors help tailor recommendations — read <a href='/articles/buy-through-agent-or-self'>buying through an advisor vs buying online</a>.</p><p><strong>4. Continuous innovation</strong><br/>AIA adapts with technology and digital services for customers.</p><p><b>Health & Wellness</b> — AIA promotes long-term wellbeing, including programmes like <a href='/articles/aia-vitality'><b>AIA Vitality</b></a>.</p>",
    7: "<p><strong>Why choose AIA via UDONAIA.COM</strong><br/>For reliable information and advice on <a href='/articles/aia-health-good-2026'>AIA health insurance</a>, <a href='/services'>life insurance</a>, and financial planning, our team understands local needs — e.g. <a href='/articles/agent-udon-free-consult'>AIA Udon Thani</a>.</p><p><strong>Summary</strong><br/>AIA is a long-established life insurer trusted across Asia for stability, product breadth, and ongoing development.</p><p><b><u>Plan for life and health</u></b> — <a href='/contact'><b>Contact us for a free consult at udonaia.com</b></a></p>",
  },
  lo: {
    1: "<p>ໃນໂລກວາງແຜນການເງິນແລະ <b>ປະກັນໄພຊີວິດ</b> ຊື່ <b><u>AIA</u></b> ເປັນຫນຶ່ງໃນບໍລິສັດທີ່ໜ້າເຊື່ອຖືໃນອາຊີ ລວມເຖິງໄທທີ່ມີລູກຄ້າຫຼາຍລ້ານຄົນ</p><p>ບົດຄວາມນີ້ສະຫຼຸບ <b>ປະຫວັດແລະຂໍ້ມູນບໍລິສັດ AIA</b> ເພື່ອຊ່ວຍໃຫ້ທ່ານຕັດສິນໃຈເລືອກແຜນເຊັ່ນ <a href='/articles/aia-health-good-2026'><b>ປະກັນສຸຂະພາບ AIA</b></a> ຫຼື <a href='/services'><b>ປະກັນໄພຊີວິດ</b></a></p>",
    2: "<p><b>AIA</b> (<b>American International Assurance</b>) ກໍ່ຕັ້ງປີ <b><u>1919</u></b> ໂດຍ Cornelius Vander Starr ເລີ່ມທຸລະກິດປະກັນໃນອາຊີ</p><p>ສຳນັກງານແຫ່ງທຳອິດຢູ່ <u>Shanghai</u> ກ່ອນຂະຫຍາຍໄປຫຼາຍປະເທດ</p>",
    3: "<p>AIA ມີທຸລະກິດໃນອາຊີ-ແປຊິຟິກ ເຊັ່ນ:</p><ul><li>Thailand</li><li>Hong Kong</li><li>Singapore</li><li>China</li></ul><p>ປັດຈຸບັນມີລູກຄ້າຫຼາຍສິບລ້ານຄົນ ອ່ານເພີ່ມ <a href='/articles/agent-udon-free-consult'>ຕົວແທນ AIA ອຸດອນ</a></p>",
    4: "<p><b>AIA</b> ດຳເນີນທຸລະກິດໃນໄທຫຼາຍກວ່າ <b><u>80 ປີ</u></b> ເປັນບໍລິສັດປະກັນຊີວິດທີ່ມີລູກຄ້າຫຼາຍ</p><p>ຄວາມໝັ້ນຄົງທາງການເງິນແລະຜະລິດຕະພັນໃໝ່ — <a href='/services'>ປະກັນໄພຊີວິດ</a> <a href='/articles/aia-health-good-2026'>ສຸຂະພາບ</a> ແລະວາງແຜນລະຍະຍາວ</p>",
    5: "<p><strong>1. ຄວາມໝັ້ນຄົງແລະປະສົບການ</strong><br/>ຫຼາຍກວ່າ <b>100 ປີ</b> ໃນການບໍລິຫານແລະການເງິນ</p><p><strong>2. ຜະລິດຕະພັນຫຼາກຫຼາຍ</strong><br/><a href='/services'>ປະກັນໄພຊີວິດ</a> <a href='/articles/health-coverage-what'>ສຸຂະພາບ</a> <a href='/articles/cancer-treatment-cost-thailand'>ໂລກຮ້າຍແຮງ</a></p>",
    6: "<p><strong>3. ບໍລິການແລະຕົວແທນມືອາຊີບ</strong><br/><a href='/articles/buy-through-agent-or-self'>ຊື້ກັບຕົວແທນຫຼືຊື້ເອງ</a></p><p><strong>4. ນະວັດຕະກຳຕໍ່ເນື່ອງ</strong><br/>ເຕັກໂນໂລຊີແລະດິຈິຕອນ</p><p><b>Health & Wellness</b> ລວມ <a href='/articles/aia-vitality'><b>AIA Vitality</b></a></p>",
    7: "<p><strong>ເປັນຫຍັງເລືອກ AIA ຜ່ານ UDONAIA.COM</strong><br/><a href='/articles/aia-health-good-2026'>ປະກັນສຸຂະພາບ AIA</a> <a href='/services'>ປະກັນໄພຊີວິດ</a> ວາງແຜນການເງິນ <a href='/articles/agent-udon-free-consult'>AIA ອຸດອນ</a></p><p><strong>ສະຫຼຸບ</strong><br/>AIA ມີປະຫວັດຍາວແລະໄດ້ຮັບຄວາມເຊື່ອຖືໃນອາຊີ</p><p><b><u>ສົນໃຈວາງແຜນ</u></b> <a href='/contact'><b>ຕິດຕໍ່ປຶກສາຟຣີ udonaia.com</b></a></p>",
  },
}
