/**
 * เนื้อหา HTML สำหรับบทความ aiaNewHealthStandard (ไม่ใส่ใน locale JSON — unplugin-vue-i18n ห้าม HTML ใน message)
 */
export const aiaNewHealthStandardBodies: Record<
  'th' | 'en' | 'lo',
  Record<number, string>
> = {
  th: {
    1: "<p>ในช่วงไม่กี่ปีที่ผ่านมา หลายคนอาจได้ยินคำว่า <b><u>ประกันสุขภาพแบบมาตรฐานใหม่</u></b> หรือ <b>New Health Standard</b> ซึ่งเป็นรูปแบบใหม่ของ <a href='/articles/aia-health-good-2026'><b>ประกันสุขภาพ AIA</b></a> ที่ถูกออกแบบมาให้มีความชัดเจน โปร่งใส และเปรียบเทียบได้ง่ายมากขึ้น</p><p>โดยเฉพาะหากคุณกำลังมองหาแผนในพื้นที่ <a href='/articles/agent-udon-free-consult'><b>AIA อุดรธานี</b></a> การเข้าใจโครงสร้างใหม่นี้จะช่วยให้เลือกแผนได้เหมาะกับตัวเองมากขึ้น</p>",
    2: "<p><b>New Health Standard</b> คือมาตรฐานกลางของประกันสุขภาพที่กำหนดโดยหน่วยงานกำกับดูแล เพื่อให้บริษัทประกันทุกแห่งใช้โครงสร้างความคุ้มครองในรูปแบบเดียวกัน จุดประสงค์หลักคือ:</p><ul><li>ทำให้ลูกค้า <u>เปรียบเทียบแผนประกันได้ง่ายขึ้น</u></li><li>ปรับรูปแบบความคุ้มครองให้ทันสมัยตามเทคโนโลยีทางการแพทย์</li><li>เพิ่มความโปร่งใสของเงื่อนไขในกรมธรรม์</li></ul><p>หากต้องการเข้าใจว่าแผนคุ้มครองอะไรบ้างในเชิงละเอียด แนะนำอ่านเพิ่มที่ <a href='/articles/health-coverage-what'>ประกันสุขภาพครอบคลุมอะไรบ้าง</a> และปรึกษา <a href='/articles/agent-udon-free-consult'>ตัวแทน AIA อุดรธานี</a> เพื่อเทียบแผนจริง</p>",
    3: "<p><strong>1. โครงสร้างความคุ้มครองแบบเดียวกัน</strong><br/>แผนประกันจะถูกแบ่งเป็น <b><u>13 หมวดความคุ้มครอง</u></b> เช่น ค่าห้องและค่าอาหาร ค่ารักษาพยาบาล ค่าผ่าตัดและค่าบริการทางการแพทย์ ซึ่งช่วยให้ลูกค้าเข้าใจสิทธิประโยชน์ได้ง่ายขึ้น</p><p><strong>2. ครอบคลุมค่ารักษาที่สอดคล้องกับยุคปัจจุบัน</strong><br/>ค่ารักษามีแนวโน้มสูงขึ้น รูปแบบใหม่จึงออกแบบให้รองรับค่าใช้จ่ายทางการแพทย์ที่เปลี่ยนแปลงไป รายละเอียดแต่ละแผนอาจต่างกัน — ดูแนวคิดแบบเหมาจ่ายเพิ่มเติมที่ <a href='/articles/aia-lump-sum-guide'>ประกันสุขภาพ AIA เหมาจ่าย</a></p>",
    4: "<p><strong>3. มีการกำหนด “โรคทั่วไป” ชัดเจน</strong><br/>ในแผนมาตรฐานใหม่จะมีการนิยามกลุ่มโรคทั่วไป เช่น ไข้หวัด ท้องเสีย เวียนศีรษะ เพื่อกำหนดเงื่อนไขการเคลมให้ชัดเจนขึ้น</p><p><strong>4. เงื่อนไขกรมธรรม์โปร่งใสขึ้น</strong><br/>ตัวอย่างหลักการที่ลูกค้ามักสนใจ: หากกรมธรรม์มีผลคุ้มครองเกิน 2 ปี บริษัทจะไม่โต้แย้งสัญญา และการปรับเบี้ยมักอิงตามอายุและค่ารักษาโดยรวม รายละเอียดขึ้นกับกรมธรรม์จริง</p><p>เมื่อต้องใช้สิทธิ์ที่โรงพยาบาล แนะนำศึกษา <a href='/articles/hospital-aia-kk-korat'>โรงพยาบาลคู่สัญญา AIA</a> และขั้นตอน <a href='/articles/claim-nongkhai-buengkan'>การเคลมประกัน</a> ในพื้นที่ใกล้คุณ</p>",
    5: "<p>แผนในกลุ่มนี้ เช่น แผนค่ารักษาผู้ป่วยใน (IPD) แผนที่มีทั้ง IPD และ OPD หรือแผนวงเงินสูงที่เหมาะกับโรงพยาบาลเอกชน บางแผนอาจคุ้มครองยาวถึงอายุ 99 ปี และช่วยลดภาระค่าใช้จ่ายในการรักษาได้อย่างมีประสิทธิภาพ</p><p>การเลือกแผนควรดูทั้งวงเงิน เงื่อนไขรอคอย และไลฟ์สไตล์การรักษา — ดูบริการและแนวทางเช็คเบี้ยได้ที่ <a href='/services'>หน้าบริการของเรา</a></p>",
    6: "<p>แม้โครงสร้างประกันจะเป็นมาตรฐานเดียวกัน แต่ <b><u>การเลือกแผน</u></b> ยังต้องอาศัยประสบการณ์ของตัวแทนในพื้นที่</p><ul><li>เข้าใจค่ารักษาในโรงพยาบาลพื้นที่จริง</li><li>แนะนำแผนให้เหมาะกับรายได้และความเสี่ยง</li><li>ช่วยดูแลเคลมในสถานการณ์จริง</li></ul><p>อ่านเหตุผลเพิ่มเติม: <a href='/articles/agent-udon-5-reasons'>มองหาตัวแทน AIA อุดรธานี</a> และ <a href='/articles/agent-udon-free-consult'>ปรึกษาตัวแทน AIA อุดรธานีฟรี</a></p>",
    7: "<p><b>New Health Standard</b> ช่วยให้ <a href='/articles/aia-health-good-2026'><b>ประกันสุขภาพ AIA</b></a> เข้าใจง่ายขึ้น เปรียบเทียบได้ชัดเจน โปร่งใสมากขึ้น และรองรับค่ารักษาในอนาคต — เหมาะกับคนรุ่นใหม่ที่ต้องการความคุ้มครองแบบยืดหยุ่น</p><p><b><u>สนใจวางแผนประกันสุขภาพ</u></b> หากกำลังมองหาแผนที่เหมาะกับตัวเองหรืออยากคุยกับผู้เชี่ยวชาญ <a href='/contact'><b><u>ติดต่อปรึกษาฟรีที่ udonaia.com</u></b></a> ทีม <a href='/articles/agent-udon-free-consult'>AIA อุดรธานี</a> พร้อมช่วยวางแผนโดยไม่มีค่าใช้จ่ายในขั้นปรึกษา</p>",
  },
  en: {
    1: "<p>In recent years you may have heard of <b><u>the new health insurance standard</u></b> or <b>New Health Standard</b> — an updated structure for <a href='/articles/aia-health-good-2026'><b>AIA health insurance</b></a> designed to be clearer, more transparent and easier to compare.</p><p>If you are looking for coverage with <a href='/articles/agent-udon-free-consult'><b>AIA in Udon Thani</b></a>, understanding this framework helps you pick a plan that fits you better.</p>",
    2: "<p><b>New Health Standard</b> is a regulatory framework so insurers use a consistent benefit structure. Main goals:</p><ul><li>Make it <u>easier to compare plans</u></li><li>Align coverage with modern medical practice</li><li>Improve transparency of policy wording</li></ul><p>For what health insurance typically covers, see <a href='/articles/health-coverage-what'>what health insurance covers</a> and talk to an <a href='/articles/agent-udon-free-consult'>AIA advisor in Udon Thani</a> to compare real quotes.</p>",
    3: "<p><strong>1. Shared benefit structure</strong><br/>Plans are organised into <b><u>13 benefit categories</u></b> such as room and board, hospital treatment, surgery and medical services — so benefits are easier to read.</p><p><strong>2. Coverage aligned with current costs</strong><br/>Medical inflation is ongoing; the new format is designed to reflect changing costs. For sum-insured concepts, read <a href='/articles/aia-lump-sum-guide'>AIA lump-sum health insurance</a>.</p>",
    4: "<p><strong>3. Clearer definition of “simple diseases”</strong><br/>Examples such as flu, diarrhoea or dizziness help set clearer claim conditions.</p><p><strong>4. More transparent policy terms</strong><br/>Common principles include: after more than two years in force, the insurer may not contest the contract; premiums may follow age and overall medical cost trends. Always confirm wording in your actual policy.</p><p>For hospitals and claims, see <a href='/articles/hospital-aia-kk-korat'>AIA network hospitals</a> and <a href='/articles/claim-nongkhai-buengkan'>how to claim</a> in your area.</p>",
    5: "<p>Examples include inpatient (IPD) plans, combined IPD/OPD plans, or higher limits suited to private hospitals. Some plans may cover up to age 99 and help reduce out-of-pocket treatment costs effectively.</p><p>Compare limits, waiting periods and how you use care — start from our <a href='/services'>services page</a> for quotes and guidance.</p>",
    6: "<p>Even with the same regulatory structure, <b><u>choosing the right plan</u></b> still depends on local experience.</p><ul><li>Understanding real hospital costs in the area</li><li>Matching plans to income and risk</li><li>Support with real-world claims</li></ul><p>Read more: <a href='/articles/agent-udon-5-reasons'>why choose a local AIA advisor</a> and <a href='/articles/agent-udon-free-consult'>free consultation in Udon Thani</a>.</p>",
    7: "<p><b>New Health Standard</b> helps <a href='/articles/aia-health-good-2026'><b>AIA health insurance</b></a> stay easier to understand, compare and trust — and better aligned with future medical costs.</p><p><b><u>Interested in planning health cover?</u></b> <a href='/contact'><b><u>Contact us for a free consult at udonaia.com</u></b></a>. Our <a href='/articles/agent-udon-free-consult'>AIA Udon Thani</a> team can help at no charge for the advisory step.</p>",
  },
  lo: {
    1: "<p>ໃນຊ່ວງຫຼາຍປີຜ່ານມາ ຫຼາຍຄົນອາດໄດ້ຍິນຄຳວ່າ <b><u>ປະກັນສຸຂະພາບມາດຕະຖານໃໝ່</u></b> ຫຼື <b>New Health Standard</b> ຊຶ່ງເປັນຮູບແບບໃຫມ່ຂອງ <a href='/articles/aia-health-good-2026'><b>ປະກັນສຸຂະພາບ AIA</b></a> ທີ່ອອກແບບໃຫ້ຊັດເຈນ ໂປ່ງໃສ ແລະປຽບທຽບໄດ້ງ່າຍຂຶ້ນ</p><p>ໂດຍສະເພາະຖ້າທ່ານກຳລັງຊອກແຜນໃນພື້ນທີ່ <a href='/articles/agent-udon-free-consult'><b>AIA ອຸດອນ</b></a> ການເຂົ້າໃຈໂຄງສ້າງນີ້ຈະຊ່ວຍໃຫ້ເລືອກແຜນໄດ້ເໝາະກັບຕົວເອງ</p>",
    2: "<p><b>New Health Standard</b> ແມ່ນມາດຕະຖານກາງທີ່ຫນ່ວຍງານກຳກັບກຳນົດ ເພື່ອໃຫ້ບໍລິສັດປະກັນໃຊ້ໂຄງສ້າງຄວາມຄຸ້ມຄ່າແບບດຽວກັນ ຈຸດປະສົງຫຼັກ:</p><ul><li>ເຮັດໃຫ້ <u>ປຽບທຽບແຜນປະກັນໄດ້ງ່າຍຂຶ້ນ</u></li><li>ປັບຄວາມຄຸ້ມຄ່າໃຫ້ທັນສະໄໝກັບເຕັກໂນໂລຊີການແພດ</li><li>ເພີ່ມຄວາມໂປ່ງໃສຂອງເງື່ອນໄຂໃນກົດຫມາຍ</li></ul><p>ຢາກຮູ້ວ່າປະກັນສຸຂະພາບຄຸ້ມຫຍັງ ອ່ານ <a href='/articles/health-coverage-what'>ປະກັນສຸຂະພາບຄຸ້ມຫຍັງແດ່</a> ແລະປຶກສາ <a href='/articles/agent-udon-free-consult'>ຕົວແທນ AIA ອຸດອນ</a></p>",
    3: "<p><strong>1. ໂຄງສ້າງຄວາມຄຸ້ມຄ່າແບບດຽວກັນ</strong><br/>ແຜນຖືກແບ່ງເປັນ <b><u>13 ຫມວດຄວາມຄຸ້ມຄ່າ</u></b> ເຊັ່ນ ຄ່າຫ້ອງ ແລະອາຫານ ຄ່າຮັກສາພະຍາບານ ຄ່າຜ່າຕັດ ແລະຄ່າບໍລິການທາງການແພດ</p><p><strong>2. ຄຸ້ມຄ່າຮັກສາທີ່ສອດຄ່ອງກັບຍຸກປັດຈຸບັນ</strong><br/>ຄ່າຮັກມີແນວໂນ້ມສູງຂຶ້ນ ຮູບແບບໃໝ່ອອກແບບໃຫ້ຮອງຮັບຄ່າໃຊ້ຈ່າຍທີ່ປ່ຽນແປງ ອ່ານເພີ່ມ <a href='/articles/aia-lump-sum-guide'>ປະກັນສຸຂະພາບ AIA ແບບເບີ້ຍລວມ</a></p>",
    4: "<p><strong>3. ກຳນົດ “ໂລກທົ່ວໄປ” ຊັດເຈນ</strong><br/>ຕົວຢ່າງ ໄຂ້ຫວັດ ທ້ອງເສຍ ເວຍນຫົວ ເພື່ອກຳນົດເງື່ອນໄຂການເຄລມໃຫ້ຊັດຂຶ້ນ</p><p><strong>4. ເງື່ອນໄຂໂປ່ງໃສຂຶ້ນ</strong><br/>ຕົວຢ່າງທີ່ນິຍົມສົນໃຈ: ຖ້າກົດຫມາຍມີຜົນຄຸ້ມຄ່າເກີນ 2 ປີ ບໍລິສັດອາດບໍ່ໂຕ້ຖຽງສັນຍາ; ຄ່າເບີ້ຍອາດອີງອາຍຸແລະຄ່າຮັກສາໂດຍລວມ ກວດສອບກົດຫມາຍຈິງຂອງທ່ານ</p><p>ໂຮງໝໍແລະເຄລມ: <a href='/articles/hospital-aia-kk-korat'>ໂຮງໝໍຄູ່ສັນຍາ AIA</a> ແລະ <a href='/articles/claim-nongkhai-buengkan'>ຂັ້ນຕອນການເຄລມ</a></p>",
    5: "<p>ຕົວຢ່າງ ແຜນຜູ້ປ່ວຍໃນໂຮງໝໍ (IPD) ແຜນທີ່ມີທັງ IPD ແລະ OPD ຫຼືແຜນວົງເງິນສູງເໝາະກັບໂຮງໝໍເອກະຊົນ ບາງແຜນອາດຄຸ້ມຄ່າຍາວເຖິງອາຍຸ 99 ປີ</p><p>ເລືອກວົງເງິນ ເວລາລໍຖ້າ ແລະວິທີໃຊ້ສິດ — ເລີ່ມຈາກ <a href='/services'>ໜ້າບໍລິການ</a> ຂອງພວກເຮົາ</p>",
    6: "<p>ແມ້ໂຄງສ້າງຈະເປັນມາດຕະຖານດຽວກັນ ແຕ່ <b><u>ການເລືອກແຜນທີ່ເໝາະ</u></b> ຍັງຕ້ອງອາໄສປະສົບການທ້ອງຖິ່ນ</p><ul><li>ເຂົ້າໃຈຄ່າຮັກສາໃນໂຮງໝໍພື້ນທີ່ຈິງ</li><li>ແນະນຳແຜນຕາມລາຍໄດ້ແລະຄວາມສ່ຽງ</li><li>ຊ່ວຍດູແລເຄລມໃນສະຖານະການຈິງ</li></ul><p>ອ່ານເພີ່ມ: <a href='/articles/agent-udon-5-reasons'>ເຫດຜົນເລືອກຕົວແທນ AIA ອຸດອນ</a> ແລະ <a href='/articles/agent-udon-free-consult'>ປຶກສາຟຣີກັບຕົວແທນ</a></p>",
    7: "<p><b>New Health Standard</b> ຊ່ວຍໃຫ້ <a href='/articles/aia-health-good-2026'><b>ປະກັນສຸຂະພາບ AIA</b></a> ເຂົ້າໃຈງ່າຍ ປຽບທຽບໄດ້ຊັດ ໂປ່ງໃສຂຶ້ນ ແລະຮອງຮັບຄ່າຮັກສາໃນອະນາຄົດ</p><p><b><u>ສົນໃຈວາງແຜນປະກັນສຸຂະພາບ</u></b> <a href='/contact'><b><u>ຕິດຕໍ່ປຶກສາຟຣີທີ່ udonaia.com</u></b></a> ທີມ <a href='/articles/agent-udon-free-consult'>AIA ອຸດອນ</a> ພ້ອມຊ່ວຍໂດຍບໍ່ມີຄ່າປຶກສາ</p>",
  },
}
